/**
 * @vayu/shared — Ship Database
 *
 * Comprehensive static data for all playable Elite Dangerous ships.
 * Includes base stats, hardpoint layouts, and subjective role ratings.
 *
 * Data sourced from:
 * - EDSY.org / Coriolis.io ship specs
 * - Elite Dangerous Wiki
 * - In-game values (base, unengineered unless noted)
 *
 * The `id` field matches the journal's Ship field (ShipType internal name).
 */

// ---------------------------------------------------------------------------
// Ship Data Interface
// ---------------------------------------------------------------------------

/** Static reference data for a single ship model. */
export interface ShipData {
  /** Internal ED journal name (e.g. 'SideWinder', 'CobraMkIII'). */
  id: string;
  /** Human-readable display name (e.g. 'Sidewinder Mk I'). */
  displayName: string;
  /** Ship manufacturer. */
  manufacturer: string;
  /** Landing pad size class. */
  class: 'Small' | 'Medium' | 'Large';
  /** Base purchase cost in credits (unengineered, stock). */
  cost: number;
  /** Approximate maximum jump range in LY (fully engineered). */
  maxJumpRange: number;
  /** Weapon hardpoint counts by size. */
  hardpoints: { small: number; medium: number; large: number; huge: number };
  /** Number of optional internal module slots. */
  optionalSlots: number;
  /** Total crew seats including pilot (1 = solo only). */
  crewSeats: number;
  /** Maximum cargo capacity in tons (largest racks, no shield). */
  maxCargo: number;
  /** Subjective combat rating (1-10). */
  combatRating: number;
  /** Subjective exploration rating (1-10). */
  explorationRating: number;
  /** Subjective trading/hauling rating (1-10). */
  tradingRating: number;
  /** Subjective mining rating (1-10). */
  miningRating: number;
}

// ---------------------------------------------------------------------------
// Ship Database
// ---------------------------------------------------------------------------

/**
 * Complete database of all playable ships in Elite Dangerous.
 * Indexed by journal ShipType identifier.
 */
export const SHIPS: readonly ShipData[] = [
  // -------------------------------------------------------------------------
  // Starter / Small Ships
  // -------------------------------------------------------------------------
  {
    id: 'SideWinder',
    displayName: 'Sidewinder Mk I',
    manufacturer: 'Faulcon DeLacy',
    class: 'Small',
    cost: 32_000,
    maxJumpRange: 35,
    hardpoints: { small: 2, medium: 0, large: 0, huge: 0 },
    optionalSlots: 3,
    crewSeats: 1,
    maxCargo: 16,
    combatRating: 2,
    explorationRating: 3,
    tradingRating: 1,
    miningRating: 1,
  },
  {
    id: 'Eagle',
    displayName: 'Eagle Mk II',
    manufacturer: 'Core Dynamics',
    class: 'Small',
    cost: 44_800,
    maxJumpRange: 33,
    hardpoints: { small: 1, medium: 0, large: 0, huge: 0 },
    optionalSlots: 2,
    crewSeats: 1,
    maxCargo: 4,
    combatRating: 4,
    explorationRating: 2,
    tradingRating: 1,
    miningRating: 1,
  },
  {
    id: 'Empire_Eagle',
    displayName: 'Imperial Eagle',
    manufacturer: 'Gutamaya',
    class: 'Small',
    cost: 110_830,
    maxJumpRange: 34,
    hardpoints: { small: 2, medium: 1, large: 0, huge: 0 },
    optionalSlots: 2,
    crewSeats: 1,
    maxCargo: 8,
    combatRating: 5,
    explorationRating: 2,
    tradingRating: 1,
    miningRating: 1,
  },
  {
    id: 'Hauler',
    displayName: 'Hauler',
    manufacturer: 'Zorgon Peterson',
    class: 'Small',
    cost: 52_720,
    maxJumpRange: 52,
    hardpoints: { small: 1, medium: 0, large: 0, huge: 0 },
    optionalSlots: 3,
    crewSeats: 1,
    maxCargo: 26,
    combatRating: 1,
    explorationRating: 6,
    tradingRating: 2,
    miningRating: 1,
  },
  {
    id: 'Adder',
    displayName: 'Adder',
    manufacturer: 'Zorgon Peterson',
    class: 'Small',
    cost: 87_810,
    maxJumpRange: 40,
    hardpoints: { small: 2, medium: 1, large: 0, huge: 0 },
    optionalSlots: 3,
    crewSeats: 2,
    maxCargo: 30,
    combatRating: 3,
    explorationRating: 4,
    tradingRating: 2,
    miningRating: 2,
  },
  {
    id: 'Viper',
    displayName: 'Viper Mk III',
    manufacturer: 'Faulcon DeLacy',
    class: 'Small',
    cost: 142_930,
    maxJumpRange: 33,
    hardpoints: { small: 2, medium: 2, large: 0, huge: 0 },
    optionalSlots: 3,
    crewSeats: 1,
    maxCargo: 18,
    combatRating: 6,
    explorationRating: 2,
    tradingRating: 1,
    miningRating: 1,
  },
  {
    id: 'Viper_MkIV',
    displayName: 'Viper Mk IV',
    manufacturer: 'Faulcon DeLacy',
    class: 'Small',
    cost: 437_930,
    maxJumpRange: 37,
    hardpoints: { small: 2, medium: 2, large: 0, huge: 0 },
    optionalSlots: 4,
    crewSeats: 1,
    maxCargo: 50,
    combatRating: 5,
    explorationRating: 3,
    tradingRating: 2,
    miningRating: 2,
  },
  {
    id: 'CobraMkIII',
    displayName: 'Cobra Mk III',
    manufacturer: 'Faulcon DeLacy',
    class: 'Small',
    cost: 349_720,
    maxJumpRange: 42,
    hardpoints: { small: 2, medium: 2, large: 0, huge: 0 },
    optionalSlots: 4,
    crewSeats: 2,
    maxCargo: 60,
    combatRating: 5,
    explorationRating: 5,
    tradingRating: 3,
    miningRating: 3,
  },
  {
    id: 'CobraMkIV',
    displayName: 'Cobra Mk IV',
    manufacturer: 'Faulcon DeLacy',
    class: 'Small',
    cost: 764_720,
    maxJumpRange: 36,
    hardpoints: { small: 2, medium: 1, large: 0, huge: 0 },
    optionalSlots: 6,
    crewSeats: 2,
    maxCargo: 88,
    combatRating: 4,
    explorationRating: 3,
    tradingRating: 4,
    miningRating: 3,
  },
  {
    id: 'DiamondBack',
    displayName: 'Diamondback Scout',
    manufacturer: 'Lakon Spaceways',
    class: 'Small',
    cost: 564_330,
    maxJumpRange: 47,
    hardpoints: { small: 2, medium: 2, large: 0, huge: 0 },
    optionalSlots: 3,
    crewSeats: 1,
    maxCargo: 28,
    combatRating: 5,
    explorationRating: 7,
    tradingRating: 1,
    miningRating: 2,
  },
  {
    id: 'DiamondBackXL',
    displayName: 'Diamondback Explorer',
    manufacturer: 'Lakon Spaceways',
    class: 'Small',
    cost: 1_894_760,
    maxJumpRange: 70,
    hardpoints: { small: 2, medium: 1, large: 1, huge: 0 },
    optionalSlots: 4,
    crewSeats: 1,
    maxCargo: 44,
    combatRating: 4,
    explorationRating: 9,
    tradingRating: 2,
    miningRating: 3,
  },
  {
    id: 'Empire_Courier',
    displayName: 'Imperial Courier',
    manufacturer: 'Gutamaya',
    class: 'Small',
    cost: 2_542_930,
    maxJumpRange: 42,
    hardpoints: { small: 0, medium: 3, large: 0, huge: 0 },
    optionalSlots: 3,
    crewSeats: 1,
    maxCargo: 22,
    combatRating: 6,
    explorationRating: 4,
    tradingRating: 1,
    miningRating: 1,
  },
  {
    id: 'Vulture',
    displayName: 'Vulture',
    manufacturer: 'Core Dynamics',
    class: 'Small',
    cost: 4_925_620,
    maxJumpRange: 37,
    hardpoints: { small: 0, medium: 0, large: 2, huge: 0 },
    optionalSlots: 3,
    crewSeats: 2,
    maxCargo: 24,
    combatRating: 8,
    explorationRating: 2,
    tradingRating: 1,
    miningRating: 2,
  },

  // -------------------------------------------------------------------------
  // Medium Ships
  // -------------------------------------------------------------------------
  {
    id: 'Asp_Scout',
    displayName: 'Asp Scout',
    manufacturer: 'Lakon Spaceways',
    class: 'Medium',
    cost: 3_961_150,
    maxJumpRange: 45,
    hardpoints: { small: 2, medium: 2, large: 0, huge: 0 },
    optionalSlots: 4,
    crewSeats: 2,
    maxCargo: 52,
    combatRating: 3,
    explorationRating: 5,
    tradingRating: 3,
    miningRating: 3,
  },
  {
    id: 'Asp',
    displayName: 'Asp Explorer',
    manufacturer: 'Lakon Spaceways',
    class: 'Medium',
    cost: 6_661_150,
    maxJumpRange: 62,
    hardpoints: { small: 2, medium: 4, large: 0, huge: 0 },
    optionalSlots: 6,
    crewSeats: 2,
    maxCargo: 128,
    combatRating: 4,
    explorationRating: 9,
    tradingRating: 5,
    miningRating: 6,
  },
  {
    id: 'Independant_Trader',
    displayName: 'Keelback',
    manufacturer: 'Lakon Spaceways',
    class: 'Medium',
    cost: 3_126_150,
    maxJumpRange: 36,
    hardpoints: { small: 2, medium: 2, large: 0, huge: 0 },
    optionalSlots: 4,
    crewSeats: 2,
    maxCargo: 98,
    combatRating: 3,
    explorationRating: 2,
    tradingRating: 4,
    miningRating: 4,
  },
  {
    id: 'Type6',
    displayName: 'Type-6 Transporter',
    manufacturer: 'Lakon Spaceways',
    class: 'Medium',
    cost: 1_045_950,
    maxJumpRange: 42,
    hardpoints: { small: 2, medium: 0, large: 0, huge: 0 },
    optionalSlots: 5,
    crewSeats: 1,
    maxCargo: 114,
    combatRating: 1,
    explorationRating: 4,
    tradingRating: 6,
    miningRating: 4,
  },
  {
    id: 'Dolphin',
    displayName: 'Dolphin',
    manufacturer: 'Saud Kruger',
    class: 'Small',
    cost: 1_337_330,
    maxJumpRange: 52,
    hardpoints: { small: 2, medium: 0, large: 0, huge: 0 },
    optionalSlots: 5,
    crewSeats: 1,
    maxCargo: 84,
    combatRating: 1,
    explorationRating: 7,
    tradingRating: 3,
    miningRating: 3,
  },
  {
    id: 'Federation_Dropship',
    displayName: 'Federal Dropship',
    manufacturer: 'Core Dynamics',
    class: 'Medium',
    cost: 14_314_210,
    maxJumpRange: 33,
    hardpoints: { small: 2, medium: 2, large: 1, huge: 0 },
    optionalSlots: 5,
    crewSeats: 2,
    maxCargo: 164,
    combatRating: 6,
    explorationRating: 2,
    tradingRating: 5,
    miningRating: 4,
  },
  {
    id: 'Federation_Dropship_MkII',
    displayName: 'Federal Assault Ship',
    manufacturer: 'Core Dynamics',
    class: 'Medium',
    cost: 19_814_210,
    maxJumpRange: 33,
    hardpoints: { small: 2, medium: 2, large: 0, huge: 0 },
    optionalSlots: 5,
    crewSeats: 2,
    maxCargo: 118,
    combatRating: 8,
    explorationRating: 2,
    tradingRating: 3,
    miningRating: 3,
  },
  {
    id: 'Federation_Gunship',
    displayName: 'Federal Gunship',
    manufacturer: 'Core Dynamics',
    class: 'Medium',
    cost: 35_814_210,
    maxJumpRange: 32,
    hardpoints: { small: 4, medium: 2, large: 1, huge: 0 },
    optionalSlots: 5,
    crewSeats: 2,
    maxCargo: 164,
    combatRating: 8,
    explorationRating: 2,
    tradingRating: 4,
    miningRating: 4,
  },
  {
    id: 'Empire_Trader',
    displayName: 'Imperial Clipper',
    manufacturer: 'Gutamaya',
    class: 'Large',
    cost: 22_295_860,
    maxJumpRange: 38,
    hardpoints: { small: 0, medium: 2, large: 2, huge: 0 },
    optionalSlots: 6,
    crewSeats: 2,
    maxCargo: 248,
    combatRating: 6,
    explorationRating: 4,
    tradingRating: 7,
    miningRating: 5,
  },
  {
    id: 'TypeX',
    displayName: 'Alliance Chieftain',
    manufacturer: 'Lakon Spaceways',
    class: 'Medium',
    cost: 19_382_250,
    maxJumpRange: 33,
    hardpoints: { small: 3, medium: 1, large: 2, huge: 0 },
    optionalSlots: 5,
    crewSeats: 2,
    maxCargo: 88,
    combatRating: 8,
    explorationRating: 2,
    tradingRating: 3,
    miningRating: 3,
  },
  {
    id: 'TypeX_3',
    displayName: 'Alliance Challenger',
    manufacturer: 'Lakon Spaceways',
    class: 'Medium',
    cost: 30_472_250,
    maxJumpRange: 32,
    hardpoints: { small: 3, medium: 3, large: 1, huge: 0 },
    optionalSlots: 5,
    crewSeats: 2,
    maxCargo: 96,
    combatRating: 8,
    explorationRating: 2,
    tradingRating: 3,
    miningRating: 3,
  },
  {
    id: 'TypeX_2',
    displayName: 'Alliance Crusader',
    manufacturer: 'Lakon Spaceways',
    class: 'Medium',
    cost: 22_866_340,
    maxJumpRange: 32,
    hardpoints: { small: 2, medium: 2, large: 2, huge: 0 },
    optionalSlots: 5,
    crewSeats: 3,
    maxCargo: 88,
    combatRating: 7,
    explorationRating: 2,
    tradingRating: 3,
    miningRating: 3,
  },
  {
    id: 'FerDeLance',
    displayName: 'Fer-de-Lance',
    manufacturer: 'Zorgon Peterson',
    class: 'Medium',
    cost: 51_567_040,
    maxJumpRange: 34,
    hardpoints: { small: 0, medium: 4, large: 0, huge: 1 },
    optionalSlots: 4,
    crewSeats: 2,
    maxCargo: 50,
    combatRating: 9,
    explorationRating: 2,
    tradingRating: 2,
    miningRating: 2,
  },
  {
    id: 'Mamba',
    displayName: 'Mamba',
    manufacturer: 'Zorgon Peterson',
    class: 'Medium',
    cost: 55_867_040,
    maxJumpRange: 32,
    hardpoints: { small: 2, medium: 2, large: 0, huge: 1 },
    optionalSlots: 4,
    crewSeats: 2,
    maxCargo: 32,
    combatRating: 8,
    explorationRating: 2,
    tradingRating: 1,
    miningRating: 2,
  },
  {
    id: 'Python',
    displayName: 'Python',
    manufacturer: 'Faulcon DeLacy',
    class: 'Medium',
    cost: 56_978_180,
    maxJumpRange: 40,
    hardpoints: { small: 2, medium: 2, large: 1, huge: 0 },
    optionalSlots: 6,
    crewSeats: 2,
    maxCargo: 284,
    combatRating: 7,
    explorationRating: 4,
    tradingRating: 8,
    miningRating: 8,
  },
  {
    id: 'Python_NX',
    displayName: 'Python Mk II',
    manufacturer: 'Faulcon DeLacy',
    class: 'Medium',
    cost: 67_800_000,
    maxJumpRange: 42,
    hardpoints: { small: 2, medium: 2, large: 1, huge: 0 },
    optionalSlots: 7,
    crewSeats: 2,
    maxCargo: 198,
    combatRating: 7,
    explorationRating: 5,
    tradingRating: 7,
    miningRating: 7,
  },
  {
    id: 'Krait_MkII',
    displayName: 'Krait Mk II',
    manufacturer: 'Faulcon DeLacy',
    class: 'Medium',
    cost: 45_814_210,
    maxJumpRange: 42,
    hardpoints: { small: 2, medium: 2, large: 1, huge: 0 },
    optionalSlots: 5,
    crewSeats: 3,
    maxCargo: 200,
    combatRating: 8,
    explorationRating: 5,
    tradingRating: 6,
    miningRating: 7,
  },
  {
    id: 'Krait_Light',
    displayName: 'Krait Phantom',
    manufacturer: 'Faulcon DeLacy',
    class: 'Medium',
    cost: 37_472_250,
    maxJumpRange: 60,
    hardpoints: { small: 2, medium: 2, large: 0, huge: 0 },
    optionalSlots: 5,
    crewSeats: 2,
    maxCargo: 200,
    combatRating: 5,
    explorationRating: 8,
    tradingRating: 6,
    miningRating: 5,
  },
  {
    id: 'Orca',
    displayName: 'Orca',
    manufacturer: 'Saud Kruger',
    class: 'Large',
    cost: 48_539_890,
    maxJumpRange: 45,
    hardpoints: { small: 0, medium: 2, large: 1, huge: 0 },
    optionalSlots: 5,
    crewSeats: 2,
    maxCargo: 192,
    combatRating: 3,
    explorationRating: 5,
    tradingRating: 6,
    miningRating: 3,
  },

  // -------------------------------------------------------------------------
  // Large Ships
  // -------------------------------------------------------------------------
  {
    id: 'Type7',
    displayName: 'Type-7 Transporter',
    manufacturer: 'Lakon Spaceways',
    class: 'Large',
    cost: 17_472_250,
    maxJumpRange: 39,
    hardpoints: { small: 4, medium: 0, large: 0, huge: 0 },
    optionalSlots: 6,
    crewSeats: 1,
    maxCargo: 310,
    combatRating: 1,
    explorationRating: 3,
    tradingRating: 8,
    miningRating: 5,
  },
  {
    id: 'Type8',
    displayName: 'Type-8 Transporter',
    manufacturer: 'Lakon Spaceways',
    class: 'Large',
    cost: 38_000_000,
    maxJumpRange: 42,
    hardpoints: { small: 2, medium: 2, large: 1, huge: 0 },
    optionalSlots: 8,
    crewSeats: 2,
    maxCargo: 406,
    combatRating: 3,
    explorationRating: 4,
    tradingRating: 9,
    miningRating: 7,
  },
  {
    id: 'Type9',
    displayName: 'Type-9 Heavy',
    manufacturer: 'Lakon Spaceways',
    class: 'Large',
    cost: 76_555_840,
    maxJumpRange: 33,
    hardpoints: { small: 2, medium: 2, large: 1, huge: 0 },
    optionalSlots: 8,
    crewSeats: 3,
    maxCargo: 790,
    combatRating: 2,
    explorationRating: 1,
    tradingRating: 10,
    miningRating: 7,
  },
  {
    id: 'Type9_Military',
    displayName: 'Type-10 Defender',
    manufacturer: 'Lakon Spaceways',
    class: 'Large',
    cost: 124_755_340,
    maxJumpRange: 30,
    hardpoints: { small: 3, medium: 3, large: 3, huge: 1 },
    optionalSlots: 8,
    crewSeats: 3,
    maxCargo: 532,
    combatRating: 6,
    explorationRating: 1,
    tradingRating: 7,
    miningRating: 7,
  },
  {
    id: 'BelugaLiner',
    displayName: 'Beluga Liner',
    manufacturer: 'Saud Kruger',
    class: 'Large',
    cost: 84_532_760,
    maxJumpRange: 42,
    hardpoints: { small: 0, medium: 4, large: 1, huge: 0 },
    optionalSlots: 7,
    crewSeats: 3,
    maxCargo: 370,
    combatRating: 3,
    explorationRating: 6,
    tradingRating: 7,
    miningRating: 4,
  },
  {
    id: 'Cutter',
    displayName: 'Imperial Cutter',
    manufacturer: 'Gutamaya',
    class: 'Large',
    cost: 208_969_450,
    maxJumpRange: 38,
    hardpoints: { small: 0, medium: 2, large: 2, huge: 1 },
    optionalSlots: 8,
    crewSeats: 3,
    maxCargo: 792,
    combatRating: 7,
    explorationRating: 3,
    tradingRating: 10,
    miningRating: 8,
  },
  {
    id: 'Federation_Corvette',
    displayName: 'Federal Corvette',
    manufacturer: 'Core Dynamics',
    class: 'Large',
    cost: 187_969_450,
    maxJumpRange: 33,
    hardpoints: { small: 2, medium: 1, large: 0, huge: 2 },
    optionalSlots: 8,
    crewSeats: 3,
    maxCargo: 616,
    combatRating: 10,
    explorationRating: 2,
    tradingRating: 7,
    miningRating: 6,
  },
  {
    id: 'Anaconda',
    displayName: 'Anaconda',
    manufacturer: 'Faulcon DeLacy',
    class: 'Large',
    cost: 146_969_450,
    maxJumpRange: 84,
    hardpoints: { small: 3, medium: 2, large: 1, huge: 1 },
    optionalSlots: 9,
    crewSeats: 3,
    maxCargo: 468,
    combatRating: 8,
    explorationRating: 10,
    tradingRating: 8,
    miningRating: 8,
  },
  {
    id: 'Mandalay',
    displayName: 'Mandalay',
    manufacturer: 'Zorgon Peterson',
    class: 'Medium',
    cost: 72_000_000,
    maxJumpRange: 80,
    hardpoints: { small: 2, medium: 2, large: 0, huge: 0 },
    optionalSlots: 7,
    crewSeats: 2,
    maxCargo: 100,
    combatRating: 3,
    explorationRating: 10,
    tradingRating: 3,
    miningRating: 3,
  },
] as const;

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

/** Map from ship ID (journal name) to ShipData for O(1) lookups. */
export const SHIP_BY_ID: ReadonlyMap<string, ShipData> = new Map(
  SHIPS.map((s) => [s.id, s]),
);

/**
 * Get ship data by journal ID.
 * Returns undefined if the ID is not recognized.
 */
export function getShipById(id: string): ShipData | undefined {
  return SHIP_BY_ID.get(id);
}

/**
 * Get ship data by display name (case-insensitive).
 * Returns undefined if no match is found.
 */
export function getShipByName(displayName: string): ShipData | undefined {
  const lower = displayName.toLowerCase();
  return SHIPS.find((s) => s.displayName.toLowerCase() === lower);
}
